# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aiChat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'aiChat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61iChat.proto\"M\n\x08userData\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x0f\n\x07heading\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x10\n\x08newsDate\x18\x04 \x01(\t\":\n\x16SaveToVectorDbResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\"*\n\x06prompt\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\">\n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x32\x64\n\x06\x41iChat\x12\x36\n\x0eSaveToVectorDb\x12\t.userData\x1a\x17.SaveToVectorDbResponse\"\x00\x12\"\n\x04\x43hat\x12\x07.prompt\x1a\r.ChatResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiChat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERDATA']._serialized_start=16
  _globals['_USERDATA']._serialized_end=93
  _globals['_SAVETOVECTORDBRESPONSE']._serialized_start=95
  _globals['_SAVETOVECTORDBRESPONSE']._serialized_end=153
  _globals['_PROMPT']._serialized_start=155
  _globals['_PROMPT']._serialized_end=197
  _globals['_CHATRESPONSE']._serialized_start=199
  _globals['_CHATRESPONSE']._serialized_end=261
  _globals['_AICHAT']._serialized_start=263
  _globals['_AICHAT']._serialized_end=363
# @@protoc_insertion_point(module_scope)
