# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aiChat_pb2 as aiChat__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in aiChat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveToVectorDb = channel.unary_unary(
                '/AiChat/SaveToVectorDb',
                request_serializer=aiChat__pb2.userData.SerializeToString,
                response_deserializer=aiChat__pb2.SaveToVectorDbResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_stream(
                '/AiChat/Chat',
                request_serializer=aiChat__pb2.prompt.SerializeToString,
                response_deserializer=aiChat__pb2.ChatResponse.FromString,
                _registered_method=True)


class AiChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveToVectorDb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveToVectorDb': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveToVectorDb,
                    request_deserializer=aiChat__pb2.userData.FromString,
                    response_serializer=aiChat__pb2.SaveToVectorDbResponse.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=aiChat__pb2.prompt.FromString,
                    response_serializer=aiChat__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AiChat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AiChat', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiChat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveToVectorDb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AiChat/SaveToVectorDb',
            aiChat__pb2.userData.SerializeToString,
            aiChat__pb2.SaveToVectorDbResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/AiChat/Chat',
            aiChat__pb2.prompt.SerializeToString,
            aiChat__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
